const dotenv = require("dotenv");
dotenv.config();
const env = {
  DATA_MANAGEMENT_SERVICE_PORT: process.env.DATA_MANAGEMENT_SERVICE_PORT,
  DATA_MANAGEMENT_BASE_ADDRESS: process.env.DATA_MANAGEMENT_BASE_ADRESS,

  JWT_SECRET: process.env.JWT_SECRET,

  // mongodb
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_HOST: process.env.DB_HOST,

  // firebase
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
};

module.exports = env;
